import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import ButtonBack from "../components/buttonback";

export default function Sacarmusculo() {
    const router = useRouter();
    const {peso,estatura,sexo,objetivo} = router.query;

    if(sexo=="hombre"){
       return(
        <div>
        <Head>
        <title>Mantenerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center min-h-screen items-center bg-white md:flex-row flex-col">
      <div className="text-center">
      <h1 className="text-4xl font-bold text-center p-6 md:text-4xl "> <span className='text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-green-500'> Sistema Experto </span> entrenador gimnasio
     </h1>
     <span className="font-bebas-neue text-6xl text-yellow-400">SACAR MUSCULO</span>
     <span className=" font-bebas-neue"> {peso} KG</span>
     <h2 className=" font-bebas-neue"> {sexo}</h2>
     <ButtonBack/>
      </div>
  <div className="w-full">
  <div  className="flex flex-col">
  <div  className="overflow-x-auto sm:-mx-6 lg:-mx-5">
    <div  className="py-2 inline-block min-w-full sm:px-6 lg:px-5">
      <div  className="overflow-hidden">
        <table  className="min-w-full">
          <thead  className="border-b">
            <tr>
              <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Parte del cuerpo 
              </th>
              <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Ejercicio
              </th>
              <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Serie
              </th>
              <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Repeticiones
              </th>
            </tr>
          </thead>
          <tbody>
            <tr  className="border-b">
              <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Quadriceps/Gluteos</td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                Leg Press (Prensa)
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 5
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 15
              </td>
              
            </tr>
            <tr  className="bg-white border-b">
              <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Biceps Femoral</td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                Maquina de biceps Femoral
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 5
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 15
              </td>
            </tr>
  

            <tr  className="bg-white border-b">
              <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                Pecho</td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
               Pecho en banco plano
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 8
              </td>
              <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 15
              </td>
            </tr>
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
  </div>

            </main>
        </div>
       )
    }else{
        return(
          <div>
          <Head>
          <title>Mantenerse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex justify-center min-h-screen items-center bg-white md:flex-row flex-col">
        <div className="text-center">
        <h1 className="text-4xl font-bold text-center p-6 md:text-4xl "> <span className='text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-green-500'> Sistema Experto </span> entrenador gimnasio
       </h1>
       <span className="font-bebas-neue text-6xl text-yellow-400">SACAR MUSCULO</span>
       <span className=" font-bebas-neue"> {peso} KG</span>
       <h2 className=" font-bebas-neue"> {sexo}</h2>
       <ButtonBack/>
        </div>
    <div className="w-full">
    <div  className="flex flex-col">
    <div  className="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div  className="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div  className="overflow-hidden">
          <table  className="min-w-full">
            <thead  className="border-b">
              <tr>
                <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Parte del cuerpo 
                </th>
                <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Ejercicio
                </th>
                <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Serie
                </th>
                <th scope="col"  className="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Repeticiones
                </th>
              </tr>
            </thead>
            <tbody>
              <tr  className="border-b">
                <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Quadriceps/Gluteos</td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  Leg Press (Prensa)
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   8
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   15
                </td>
                
              </tr>
              <tr  className="bg-white border-b">
                <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Biceps Femoral</td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  Maquina de biceps Femoral
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   8
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   15
                </td>
              </tr>
              <tr  className="bg-white border-b">
                <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"> Espalda superior</td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 Remo con cable sentado
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   5
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   12
                </td>
              </tr>
              <tr  className="bg-white border-b">
                <td  className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  Pecho</td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 Pecho en banco plano
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                 5
                </td>
                <td  className="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                   12
                </td>
              </tr>
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
    </div>
  
              </main>
          </div>
        )
    }
  }